name: raiser

packages:
  - packages/**

ignore:
  - packages/raiser/example
  - packages/raiser_generator/example

command:
  bootstrap:
    # Let Melos write `pubspec_overrides.yaml` files to link local packages
    # while keeping published `pubspec.yaml` files free of path dependencies.
    usePubspecOverrides: true

scripts:
  test:
    run: melos exec --fail-fast -- dart test
    description: Run all package tests.

  analyze:
    run: melos exec --fail-fast -- dart analyze .
    description: Run static analysis in all packages.
