include: package:lints/recommended.yaml

formatter:
  # Keep trailing commas.
  trailing_commas: preserve

  # Set the maximum line length.
  page_width: 160

# Customize additional linter rules.
linter:
  # Specify rules to be enabled or disabled.
  rules:
    # **Style Rules**
    # Enforce using const constructors where possible.
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    # Prefer single quotes over double quotes where possible.
    prefer_single_quotes: true

    # Enforce a consistent type definition for variables.
    always_specify_types: false

    # **Best Practices**
    # Avoid using dynamic types.
    avoid_dynamic_calls: true

    # Avoid using print statements in production code. In example code this is fine though.
    avoid_print: false

    # Prefer using the `final` keyword for variables that are not reassigned.
    prefer_final_fields: true
    prefer_final_locals: true

    # **Error Prevention**

    # Enforce non-nullable types where possible.
    always_require_non_null_named_parameters: true

    # **Documentation**
    # Require documentation for public members.
    public_member_api_docs: false

    # **Other Useful Rules**
    # Enforce sorting of directives (e.g., imports).
    directives_ordering: true

    # Prefer using `isEmpty` and `isNotEmpty` over `length` comparisons.
    prefer_is_empty: true
    prefer_is_not_empty: true

    # **Disable Rules (if necessary)**
    # Uncomment the following lines to disable specific lints.
    # avoid_unused_constructor_parameters: false
    # unnecessary_null_in_if_null_operators: false

# Analyzer settings.
analyzer:
  # Exclude certain files or directories from analysis.
  exclude:
    - "**/*.g.dart"
    - "**/build/**"
    - "**/generated/**"
    - "**/mocks/**"
    - "**/*.freezed.dart/**"

  # Language-specific analyzer strictness options.
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
